name: karsajobs

on: push

jobs:
  backend:
    name: backend code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend
        uses: actions/checkout@v2

      - name: Run karsajobs
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

